### ISSUE TITLE
FM7_BUFFER_SIZE Disagreement

### ISSUE THREAD

**Issue by robominds** [MatthewCash/libforza#3]
When using libforza, I find that I need to change FM7_BUFFER_SIZE to 311 from 312 in fm7.c. I am using FM7 (version 1.174.4791.0) on an XBox One S. My "DATA OUT PACKET FORMAT" is set to "CAR DASH".

I found this to be true for version of libforza compiled under Ubuntu 20.04 with gcc 9.3.0 and Raspberry Pi 4 (Raspbian buster) with gcc 8.3.0.

Is the 312 buffer size for a PC version of FM7 or a different XBox series?

**Comment by MatthewCash** [comment]
Can you verify that #4 fixes this issue? The PR fixes it for me. I gave little thought to FM7 when making this, but thank you for pointing this out, I will also mention the two UDP out modes in the readme.

**Comment by robominds** [comment]
#4 fixes the this issue for me as well.
